# -*- coding: utf-8 -*-
"""EHurtado_MSIS522_HW1_Part4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Ae3pSXjqEqXZ3Nvw7K8wzdtcr8YOPpg
"""

!pip -q install streamlit pyngrok

!pip -q install shap

!pip -q install tensorflow

import pandas as pd

df = pd.read_csv("prompt_attack_3class_full.csv")

print(df.shape)
print(df.columns.tolist())
df.head()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
# import json
# import joblib
# import shap
# import numpy as np
# import tensorflow as tf
# from sklearn.preprocessing import label_binarize
# from sklearn.metrics import roc_curve, auc
# from PIL import Image
# 
# def plot_note(text):
#     st.markdown(
#         f"<div style='font-size:18px; line-height:1.6; margin-top:0.25rem; margin-bottom:1rem;'>{text}</div>",
#         unsafe_allow_html=True
#     )
# 
# def render_settings_table(title, settings_dict):
#     display_df = pd.DataFrame({
#         "Setting": list(settings_dict.keys()),
#         "Value": [
#             ", ".join(map(str, v)) if isinstance(v, list) else str(v)
#             for v in settings_dict.values()
#         ]
#     })
#     st.markdown(f"#### {title}")
#     st.table(display_df.set_index("Setting"))
# 
# def build_user_input(df):
#     feature_defaults = {
#         "char_len": float(df["char_len"].mean()),
#         "word_count": float(df["word_count"].mean()),
#         "line_count": float(df["line_count"].mean()),
#         "caps_ratio": float(df["caps_ratio"].mean()),
#         "punct_density": float(df["punct_density"].mean()),
#         "non_ascii_ratio": float(df["non_ascii_ratio"].mean()),
#         "has_url": float(df["has_url"].mean()),
#         "has_email": float(df["has_email"].mean()),
#         "has_code_block": float(df["has_code_block"].mean()),
#         "has_base64_like": float(df["has_base64_like"].mean()),
#         "override_phrase_count": float(df["override_phrase_count"].mean()),
#         "jailbreak_phrase_count": float(df["jailbreak_phrase_count"].mean()),
#         "secret_keyword_count": float(df["secret_keyword_count"].mean()),
#         "exfil_phrase_count": float(df["exfil_phrase_count"].mean()),
#         "tool_keyword_count": float(df["tool_keyword_count"].mean()),
#         "harm_keyword_count": float(df["harm_keyword_count"].mean()),
#         "mentions_system_or_policy": float(df["mentions_system_or_policy"].mean()),
#         "external_destination_present": float(df["external_destination_present"].mean()),
#     }
#     return feature_defaults
# 
# @st.cache_resource
# def build_shap_artifacts(df, _xgb_model, feature_cols):
#     X_reference = df[feature_cols].copy()
# 
#     X_background = shap.sample(X_reference, 200, random_state=42)
# 
#     explainer = shap.TreeExplainer(
#         _xgb_model,
#         data=X_background,
#         feature_perturbation="interventional"
#     )
# 
#     X_summary = shap.sample(X_reference, 300, random_state=42)
# 
#     shap_values_raw = explainer.shap_values(X_summary)
# 
#     if isinstance(shap_values_raw, list):
#         shap_values_3d = np.stack(shap_values_raw, axis=2)
#     else:
#         shap_values_3d = shap_values_raw
# 
#     return explainer, X_summary, shap_values_3d
# 
# 
# def get_multiclass_shap_for_class(explainer, X_input_df, class_idx):
#     shap_values_raw = explainer.shap_values(X_input_df)
# 
#     if isinstance(shap_values_raw, list):
#         shap_values_3d = np.stack(shap_values_raw, axis=2)
#     else:
#         shap_values_3d = shap_values_raw
# 
#     shap_values_class = shap_values_3d[:, :, class_idx]
# 
#     expected_value = explainer.expected_value
#     if isinstance(expected_value, (list, np.ndarray)):
#         base_value_class = expected_value[class_idx]
#     else:
#         base_value_class = expected_value
# 
#     explanation = shap.Explanation(
#         values=shap_values_class,
#         base_values=np.repeat(base_value_class, X_input_df.shape[0]),
#         data=X_input_df.values,
#         feature_names=X_input_df.columns.tolist()
#     )
# 
#     return explanation
# 
# def plot_multiclass_roc_ovr(model, X_eval, y_true, class_names, title, label_encoder=None):
#     """
#     model: fitted classifier with predict_proba
#     X_eval: feature matrix
#     y_true: true labels (original string labels for sklearn models, string labels for XGBoost too)
#     class_names: ordered class names for the probability columns
#     label_encoder: optional, only needed for XGBoost if model outputs encoded classes
#     """
#     y_proba = model.predict_proba(X_eval)
# 
#     # For sklearn models, y_true is already string labels and class_names are strings
#     # For XGBoost, we still want to binarize against the original class names
#     y_true_bin = label_binarize(y_true, classes=class_names)
# 
#     fpr = {}
#     tpr = {}
#     roc_auc = {}
# 
#     for i, class_name in enumerate(class_names):
#         fpr[class_name], tpr[class_name], _ = roc_curve(y_true_bin[:, i], y_proba[:, i])
#         roc_auc[class_name] = auc(fpr[class_name], tpr[class_name])
# 
#     fig, ax = plt.subplots(figsize=(6.2, 4.8))
#     for class_name in class_names:
#         display_name = display_class_map.get(class_name, class_name)
#         ax.plot(
#             fpr[class_name],
#             tpr[class_name],
#             label=f"{display_name} (AUC = {roc_auc[class_name]:.2f})"
#         )
# 
#     ax.plot([0, 1], [0, 1], linestyle="--")
#     ax.set_xlabel("False Positive Rate")
#     ax.set_ylabel("True Positive Rate")
#     ax.set_title(title)
#     ax.legend(loc="lower right", fontsize=8)
#     plt.tight_layout()
#     return fig
# 
# st.set_page_config(page_title="MSIS 522 HW1 - Prompt Attack Detector", layout="wide")
# 
# # ----------------------------
# # Load data
# # ----------------------------
# @st.cache_data
# def load_data():
#     return pd.read_csv("prompt_attack_3class_full.csv")
# 
# df = load_data()
# 
# @st.cache_resource
# def load_xgb_artifacts():
#     with open("feature_columns.json", "r") as f:
#         feature_cols = json.load(f)
# 
#     xgb_model = joblib.load("xgboost_best.joblib")
#     xgb_label_encoder = joblib.load("xgboost_label_encoder.joblib")
# 
#     return xgb_model, xgb_label_encoder, feature_cols
# 
# 
# xgb_model, xgb_label_encoder, feature_cols = load_xgb_artifacts()
# xgb_explainer, X_summary, shap_values_3d_summary = build_shap_artifacts(df, xgb_model, feature_cols)
# 
# @st.cache_resource
# def load_sklearn_prediction_models():
#     logistic_model = joblib.load("logistic_regression_baseline.joblib")
#     decision_tree_model = joblib.load("decision_tree_best.joblib")
#     random_forest_model = joblib.load("random_forest_best.joblib")
# 
#     return {
#         "Logistic Regression": logistic_model,
#         "Decision Tree": decision_tree_model,
#         "Random Forest": random_forest_model
#     }
# 
# def render_prediction_outputs(pred_display, proba_df, model_name):
#     st.markdown(f"### Prediction — {model_name}")
# 
#     metric_col1, metric_col2 = st.columns(2)
#     with metric_col1:
#         st.metric("Predicted Class", pred_display)
#     with metric_col2:
#         st.metric("Top Probability", f"{proba_df.loc[0, 'Probability']:.2%}")
# 
#     left_col, right_col = st.columns([1, 1.2], gap="large")
# 
#     with left_col:
#         st.markdown("#### Class Probabilities")
#         proba_display_df = proba_df.copy()
#         proba_display_df["Probability"] = proba_display_df["Probability"].map(lambda x: f"{x:.2%}")
#         st.dataframe(proba_display_df, use_container_width=True, hide_index=True)
# 
#     with right_col:
#         fig, ax = plt.subplots(figsize=(5.8, 3.2))
#         ax.bar(proba_df["Class"], proba_df["Probability"])
#         ax.set_title(f"Probabilities — {model_name}", fontsize=14)
#         ax.set_xlabel("")
#         ax.set_ylabel("Probability")
#         ax.tick_params(axis="x", rotation=15)
#         plt.tight_layout()
#         st.pyplot(fig, clear_figure=True)
# 
# sklearn_models = load_sklearn_prediction_models()
# 
# @st.cache_resource
# def load_mlp_artifacts():
#     mlp_model = tf.keras.models.load_model("mlp_model.keras")
#     mlp_scaler = joblib.load("mlp_scaler.joblib")
#     mlp_label_encoder = joblib.load("mlp_label_encoder.joblib")
#     return mlp_model, mlp_scaler, mlp_label_encoder
# 
# 
# mlp_model, mlp_scaler, mlp_label_encoder = load_mlp_artifacts()
# 
# @st.cache_data
# def load_best_param_jsons():
#     with open("decision_tree_best_params.json", "r") as f:
#         dt_best_params = json.load(f)
# 
#     with open("random_forest_best_params.json", "r") as f:
#         rf_best_params = json.load(f)
# 
#     with open("xgboost_best_params.json", "r") as f:
#         xgb_best_params = json.load(f)
# 
#     return dt_best_params, rf_best_params, xgb_best_params
# 
# 
# dt_best_params, rf_best_params, xgb_best_params = load_best_param_jsons()
# 
# @st.cache_data
# def load_test_data():
#     test_df = pd.read_csv("test_processed.csv")
#     return test_df
# 
# test_df = load_test_data()
# X_test = test_df[feature_cols].copy()
# y_test = test_df["target_3class"].copy()
# 
# @st.cache_resource
# def load_mlp_history_images():
#     loss_img = Image.open("mlp_loss_history.png")
#     acc_img = Image.open("mlp_accuracy_history.png")
#     return loss_img, acc_img
# 
# mlp_loss_img, mlp_acc_img = load_mlp_history_images()
# 
# # Clean display labels
# display_class_map = {
#     "Benign": "Benign",
#     "Jailbreak": "Jailbreak",
#     "Injection_Exfil_ToolHijack": "Injection/Exfil/Tool Hijack"
# }
# 
# df["target_display"] = df["target_3class"].map(display_class_map).fillna(df["target_3class"])
# 
# # ----------------------------
# # Static summary data
# # ----------------------------
# class_counts = pd.DataFrame({
#     "Class": ["Benign", "Jailbreak", "Injection/Exfil/Tool Hijack"],
#     "Count": [2565, 1005, 2704]
# })
# 
# model_results = pd.DataFrame([
#     {
#         "Model": "XGBoost",
#         "Accuracy": 0.9087,
#         "Macro Precision": 0.8773,
#         "Macro Recall": 0.8726,
#         "Macro F1": 0.8749,
#         "Macro AUC-ROC": 0.9786
#     },
#     {
#         "Model": "MLP",
#         "Accuracy": 0.8694,
#         "Macro Precision": 0.8214,
#         "Macro Recall": 0.8409,
#         "Macro F1": 0.8292,
#         "Macro AUC-ROC": 0.9566
#     },
#     {
#         "Model": "Random Forest",
#         "Accuracy": 0.8631,
#         "Macro Precision": 0.8201,
#         "Macro Recall": 0.8633,
#         "Macro F1": 0.8278,
#         "Macro AUC-ROC": 0.9719
#     },
#     {
#         "Model": "Decision Tree",
#         "Accuracy": 0.8652,
#         "Macro Precision": 0.8181,
#         "Macro Recall": 0.8551,
#         "Macro F1": 0.8271,
#         "Macro AUC-ROC": 0.9415
#     },
#     {
#         "Model": "Logistic Regression",
#         "Accuracy": 0.8025,
#         "Macro Precision": 0.7528,
#         "Macro Recall": 0.7783,
#         "Macro F1": 0.7552,
#         "Macro AUC-ROC": 0.9169
#     }
# ]).sort_values("Macro F1", ascending=False).reset_index(drop=True)
# 
# # ----------------------------
# # App title
# # ----------------------------
# st.title("MSIS 522 HW1 — Prompt Attack Detection")
# st.caption(
#     "End-to-end workflow: descriptive analytics, predictive modeling, SHAP explainability, and interactive prediction."
# )
# 
# tab1, tab2, tab3, tab4 = st.tabs([
#     "Executive Summary",
#     "Descriptive Analytics",
#     "Model Performance",
#     "Explainability & Interactive Prediction"
# ])
# 
# # ----------------------------
# # Tab 1
# # ----------------------------
# with tab1:
#     st.header("Executive Summary")
#     st.write(
#         "This app presents the end-to-end workflow for prompt attack detection: dataset framing, descriptive analytics, model evaluation, SHAP explainability, and interactive prediction."
#     )
# 
#     # ----------------------------
#     # Top summary metrics
#     # ----------------------------
#     metric_col1, metric_col2, metric_col3 = st.columns(3)
#     with metric_col1:
#         st.metric("Dataset Rows", "6,274")
#     with metric_col2:
#         st.metric("Engineered Features", "18")
#     with metric_col3:
#         st.metric("Best Model", "XGBoost")
# 
#     st.divider()
# 
#     # ----------------------------
#     # Row 1
#     # ----------------------------
#     row1_col1, row1_col2 = st.columns(2, gap="large")
# 
#     with row1_col1:
#         with st.container(border=True):
#             st.subheader("Dataset and Prediction Task")
#             st.write("""
#             This project uses the Hugging Face `neuralchemy/Prompt-injection-dataset`, reframed into a
#             3-class classification problem for prompt attack detection.
#             """)
# 
#             st.write("""
#             The target variable is `target_3class`, with these classes:
#             - Benign
#             - Jailbreak
#             - Injection/Exfil/Tool Hijack
#             """)
# 
#             plot_note(
#                 "The problem was intentionally reframed as a multi-class tabular classification task so the workflow could support classical ML, explainability, and deployment."
#             )
# 
#     with row1_col2:
#         with st.container(border=True):
#             st.subheader("Why This Matters")
#             st.write("""
#             Prompt attacks can manipulate LLM systems, override safeguards, abuse tool use, or attempt to exfiltrate
#             sensitive information. Detecting these attacks matters for enterprise AI systems connected to private knowledge,
#             retrieval pipelines, or external tools.
#             """)
# 
#             plot_note(
#                 "This framing makes the project relevant to real-world enterprise AI risk, especially when language models interact with tools, policies, or sensitive context."
#             )
# 
#     st.divider()
# 
#     # ----------------------------
#     # Row 2
#     # ----------------------------
#     row2_col1, row2_col2 = st.columns(2, gap="large")
# 
#     with row2_col1:
#         with st.container(border=True):
#             st.subheader("Class Distribution")
#             st.dataframe(class_counts, use_container_width=True, hide_index=True)
# 
#             plot_note(
#                 "The dataset is moderately imbalanced, with Jailbreak as the minority class. That is why macro F1 became the most important comparison metric in Part 2."
#             )
# 
#     with row2_col2:
#         with st.container(border=True):
#             st.subheader("Feature Engineering Strategy")
#             st.write("""
#             The final engineered tabular dataset contains **18 numeric/binary features**.
#             Instead of embeddings, the feature set uses interpretable counts, ratios, and indicator-style variables such as:
#             - punctuation density
#             - caps ratio
#             - line count
#             - word count
#             - attack-related phrase counts
#             """)
# 
#             plot_note(
#                 "This choice improved interpretability and made the project much easier to explain and deploy in Streamlit."
#             )
# 
#     st.divider()
# 
#     # ----------------------------
#     # Full-width approach card
#     # ----------------------------
#     with st.container(border=True):
#         st.subheader("Workflow and Key Finding")
#         st.write("""
#         The workflow followed the full data science pipeline:
#         1. Transform raw prompt text into an interpretable tabular dataset
#         2. Perform descriptive analytics and correlation analysis
#         3. Train and compare five classification models
#         4. Use SHAP to explain the best-performing tree-based model
#         5. Build a Streamlit app to present the results interactively
#         """)
# 
#         st.success(
#             "Key finding: XGBoost was the best overall model based on macro F1, making it the strongest deployment candidate."
#         )
# 
# # ----------------------------
# # Tab 2
# # ----------------------------
# with tab2:
#     st.header("Descriptive Analytics")
#     st.write(
#         "This section summarizes the class distribution, key engineered feature patterns, and feature relationships in the processed prompt-attack dataset."
#     )
# 
#     # ----------------------------
#     # Top summary metrics
#     # ----------------------------
#     total_rows = len(df)
#     total_features = 18
#     class_counts_series = df["target_display"].value_counts()
#     minority_class = class_counts_series.idxmin()
#     minority_count = int(class_counts_series.min())
# 
#     m1, m2, m3 = st.columns(3)
#     with m1:
#         st.metric("Total Samples", f"{total_rows:,}")
#     with m2:
#         st.metric("Engineered Features", total_features)
#     with m3:
#         st.metric("Minority Class", f"{minority_class} ({minority_count:,})")
# 
#     st.divider()
# 
#     # ----------------------------
#     # Row 1: Target distribution + word count
#     # ----------------------------
#     row1_col1, row1_col2 = st.columns(2, gap="large")
# 
#     with row1_col1:
#         with st.container(border=True):
#             st.subheader("Target Distribution")
# 
#             class_order = ["Benign", "Jailbreak", "Injection/Exfil/Tool Hijack"]
#             counts = df["target_display"].value_counts().reindex(class_order)
# 
#             fig, ax = plt.subplots(figsize=(6.8, 4.2))
#             sns.barplot(x=counts.index, y=counts.values, ax=ax)
#             ax.set_title("Target Class Distribution")
#             ax.set_xlabel("")
#             ax.set_ylabel("Count")
#             for i, v in enumerate(counts.values):
#                 ax.text(i, v + 40, f"{v:,}", ha="center", fontsize=10)
#             ax.tick_params(axis="x", rotation=15)
#             plt.tight_layout()
#             st.pyplot(fig, clear_figure=True)
# 
#             plot_note(
#                 "The target is moderately imbalanced. Injection/Exfil/Tool Hijack is the largest class, Benign is close behind, and Jailbreak is much smaller. "
#                 "That is why macro F1 became the main comparison metric instead of relying only on accuracy."
#             )
# 
#     with row1_col2:
#         with st.container(border=True):
#             st.subheader("Word Count by Class")
# 
#             fig, ax = plt.subplots(figsize=(6.8, 4.2))
#             sns.violinplot(data=df, x="target_display", y="word_count", ax=ax)
#             ax.set_title("Word Count Distribution by Class")
#             ax.set_xlabel("")
#             ax.set_ylabel("Word Count")
#             ax.tick_params(axis="x", rotation=15)
#             plt.tight_layout()
#             st.pyplot(fig, clear_figure=True)
# 
#             plot_note(
#                 "Prompt length varies by class, with malicious prompts often showing broader spread and more extreme values. "
#                 "This suggests that simple structural features like length can carry useful signal."
#             )
# 
#     st.divider()
# 
#     # ----------------------------
#     # Row 2: Override phrases + secret keywords
#     # ----------------------------
#     row2_col1, row2_col2 = st.columns(2, gap="large")
# 
#     with row2_col1:
#         with st.container(border=True):
#             st.subheader("Override Phrase Count")
# 
#             fig, ax = plt.subplots(figsize=(6.8, 4.2))
#             sns.histplot(
#                 data=df,
#                 x="override_phrase_count",
#                 hue="target_display",
#                 multiple="stack",
#                 bins=10,
#                 ax=ax
#             )
#             ax.set_title("Override Phrase Count by Class")
#             ax.set_xlabel("Override Phrase Count")
#             ax.set_ylabel("Frequency")
#             plt.tight_layout()
#             st.pyplot(fig, clear_figure=True)
# 
#             plot_note(
#                 "Override-related phrases appear much more often in malicious classes than in benign prompts. "
#                 "That makes this feature a direct and interpretable signal of attempted instruction hijacking."
#             )
# 
#     with row2_col2:
#         with st.container(border=True):
#             st.subheader("Secret Keyword Count")
# 
#             fig, ax = plt.subplots(figsize=(6.8, 4.2))
#             sns.boxenplot(data=df, x="target_display", y="secret_keyword_count", ax=ax)
#             ax.set_title("Secret Keyword Count by Class")
#             ax.set_xlabel("")
#             ax.set_ylabel("Secret Keyword Count")
#             ax.tick_params(axis="x", rotation=15)
#             plt.tight_layout()
#             st.pyplot(fig, clear_figure=True)
# 
#             plot_note(
#                 "Secret-related keywords are concentrated in malicious prompts, especially injection and exfiltration behavior. "
#                 "This helps distinguish prompts that are trying to reveal hidden system instructions or sensitive content."
#             )
# 
#     st.divider()
# 
#     # ----------------------------
#     # Row 3: Correlation heatmap full width
#     # ----------------------------
#     with st.container(border=True):
#         st.subheader("Feature Correlation Heatmap")
# 
#         heatmap_cols = [
#             "word_count",
#             "char_len",
#             "line_count",
#             "punct_density",
#             "caps_ratio",
#             "override_phrase_count",
#             "secret_keyword_count",
#             "exfil_phrase_count",
#             "harm_keyword_count"
#         ]
#         corr = df[heatmap_cols].corr()
# 
#         fig, ax = plt.subplots(figsize=(10, 5.8))
#         sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f", ax=ax)
#         ax.set_title("Feature Correlation Heatmap")
#         plt.tight_layout()
#         st.pyplot(fig, clear_figure=True)
# 
#         plot_note(
#             "Most feature relationships are weak to moderate. The strongest correlations appear among length-related variables, "
#             "which suggests some redundancy, but not so much that the whole feature set collapses into one repeated signal."
#         )
# 
# # ----------------------------
# # Tab 3
# # ----------------------------
# with tab3:
#     st.header("Model Performance")
#     st.write(
#         "This section compares the five trained models, summarizes their configurations, and highlights the key performance visuals from Part 2."
#     )
# 
#     # ----------------------------
#     # Top summary metrics
#     # ----------------------------
#     best_model = model_results.iloc[0]["Model"]
#     best_macro_f1 = model_results.iloc[0]["Macro F1"]
# 
#     metric_col1, metric_col2, metric_col3 = st.columns(3)
#     with metric_col1:
#         st.metric("Best Model", best_model)
#     with metric_col2:
#         st.metric("Best Macro F1", f"{best_macro_f1:.4f}")
#     with metric_col3:
#         st.metric("Models Compared", len(model_results))
# 
#     st.divider()
# 
#     # ----------------------------
#     # Row 1: Table + Macro F1 chart
#     # ----------------------------
#     row1_col1, row1_col2 = st.columns([1.2, 1], gap="large")
# 
#     with row1_col1:
#         with st.container(border=True):
#             st.subheader("Model Comparison Table")
#             display_results = model_results.copy()
#             st.dataframe(display_results, use_container_width=True, hide_index=True)
# 
#             plot_note(
#                 "XGBoost ranked first on macro F1, followed by MLP, Random Forest, Decision Tree, and Logistic Regression."
#             )
# 
#     with row1_col2:
#         with st.container(border=True):
#             st.subheader("Macro F1 Comparison")
#             fig, ax = plt.subplots(figsize=(6.5, 4.2))
#             ax.bar(model_results["Model"], model_results["Macro F1"])
#             ax.set_title("Macro F1 Across Models")
#             ax.set_xlabel("")
#             ax.set_ylabel("Macro F1")
#             plt.xticks(rotation=20)
#             plt.tight_layout()
#             st.pyplot(fig, clear_figure=True)
# 
#             plot_note(
#                 "This chart makes the ranking visually obvious and reinforces why XGBoost became the deployment and explainability anchor model."
#             )
# 
#     st.divider()
# 
#     # ----------------------------
#     # Row 2: Hyperparameter inspection
#     # ----------------------------
#     with st.container(border=True):
#         st.subheader("Model Setup and Hyperparameter Search")
# 
#         model_setup = {
#             "XGBoost": {
#                 "summary": "Best overall model based on macro F1. Used multiclass probability outputs and delivered the strongest balance of predictive performance across classes.",
#                 "final_config": xgb_best_params,
#                 "search_space": {
#                     "n_estimators": [50, 100, 200],
#                     "max_depth": [3, 4, 5],
#                     "learning_rate": [0.01, 0.05, 0.1]
#                 }
#             },
#             "MLP": {
#                 "summary": "Neural network baseline with two hidden layers. Competitive overall, but weaker than XGBoost.",
#                 "final_config": {
#                     "hidden_layers": "128 -> 128",
#                     "activation": "ReLU",
#                     "output": "Softmax",
#                     "optimizer": "Adam",
#                     "learning_rate": 0.001,
#                     "batch_size": 32,
#                     "early_stopping_patience": 10
#                 },
#                 "search_space": {
#                     "note": "This model used a fixed architecture rather than GridSearchCV."
#                 }
#             },
#             "Random Forest": {
#                 "summary": "Strong tree ensemble model with competitive performance and better robustness than a single decision tree.",
#                 "final_config": rf_best_params,
#                 "search_space": {
#                     "n_estimators": [50, 100, 200],
#                     "max_depth": [3, 5, 8]
#                 }
#             },
#             "Decision Tree": {
#                 "summary": "Interpretable tree-based model tuned with cross-validation. Stronger than Logistic Regression, but not as strong as ensemble methods.",
#                 "final_config": dt_best_params,
#                 "search_space": {
#                     "max_depth": [3, 5, 7, 10],
#                     "min_samples_leaf": [5, 10, 20, 50]
#                 }
#             },
#             "Logistic Regression": {
#                 "summary": "Linear baseline model with balanced class weighting and L2 regularization through the default solver setup.",
#                 "final_config": {
#                     "class_weight": "balanced",
#                     "max_iter": 3000,
#                     "solver": "lbfgs"
#                 },
#                 "search_space": {
#                     "note": "No grid search used for this baseline."
#                 }
#             }
#         }
# 
#         selected_model_tab3 = st.selectbox(
#             "Select a model to inspect",
#             ["XGBoost", "MLP", "Random Forest", "Decision Tree", "Logistic Regression"],
#             key="tab3_model_select"
#         )
# 
#         selected_setup = model_setup[selected_model_tab3]
# 
#         st.markdown(f"### {selected_model_tab3}")
#         plot_note(selected_setup["summary"])
# 
#         hp_col1, hp_col2 = st.columns(2, gap="large")
#         with hp_col1:
#             render_settings_table("Final Configuration", selected_setup["final_config"])
#         with hp_col2:
#             render_settings_table("Search Space Explored", selected_setup["search_space"])
# 
#     st.divider()
# 
#     # ----------------------------
#     # Row 3: ROC curves
#     # ----------------------------
#     roc_col1, roc_col2 = st.columns(2, gap="large")
# 
#     with roc_col1:
#         with st.container(border=True):
#             st.subheader("Random Forest ROC Curves")
#             rf_fig = plot_multiclass_roc_ovr(
#                 model=sklearn_models["Random Forest"],
#                 X_eval=X_test,
#                 y_true=y_test,
#                 class_names=list(sklearn_models["Random Forest"].classes_),
#                 title="Random Forest ROC Curves"
#             )
#             st.pyplot(rf_fig, clear_figure=True)
#             plot_note(
#                 "Random Forest shows strong class separation overall, with especially strong discrimination for the larger classes."
#             )
# 
#     with roc_col2:
#         with st.container(border=True):
#             st.subheader("XGBoost ROC Curves")
#             xgb_fig = plot_multiclass_roc_ovr(
#                 model=xgb_model,
#                 X_eval=X_test,
#                 y_true=y_test,
#                 class_names=list(xgb_label_encoder.classes_),
#                 title="XGBoost ROC Curves"
#             )
#             st.pyplot(xgb_fig, clear_figure=True)
#             plot_note(
#                 "XGBoost delivers the strongest overall ROC performance, which aligns with its top macro F1 and macro AUC-ROC results."
#             )
# 
#     st.divider()
# 
#     # ----------------------------
#     # Row 4: MLP training history
#     # ----------------------------
#     hist_col1, hist_col2 = st.columns(2, gap="large")
# 
#     with hist_col1:
#         with st.container(border=True):
#             st.subheader("MLP Training History - Loss")
#             st.image(mlp_loss_img, use_container_width=True)
#             plot_note(
#                 "The loss curves show how the neural network optimized over time, with validation loss helping monitor generalization and early stopping."
#             )
# 
#     with hist_col2:
#         with st.container(border=True):
#             st.subheader("MLP Training History - Accuracy")
#             st.image(mlp_acc_img, use_container_width=True)
#             plot_note(
#                 "The accuracy curves show that the MLP learned meaningful signal from the engineered features, though its final test performance still trailed XGBoost."
#             )
# 
#     st.divider()
# 
#     # ----------------------------
#     # Final interpretation
#     # ----------------------------
#     with st.container(border=True):
#         st.subheader("Interpretation")
#         st.write("""
#         The results suggest that more flexible nonlinear models are better suited to separating benign prompts,
#         jailbreak attempts, and injection-style attacks. XGBoost produced the best overall balance of accuracy,
#         recall, and macro F1 across the three classes.
#         """)
# 
#         st.write("""
#         There is also a practical trade-off. Simpler models like Logistic Regression and Decision Tree are easier
#         to explain, while XGBoost delivers the strongest predictive performance. That trade-off is common in the
#         strange little zoo of machine learning models.
#         """)
# 
# # ----------------------------
# # Tab 4
# # ----------------------------
# with tab4:
#     st.header("Explainability & Interactive Prediction")
#     st.write(
#         "This section combines global explainability from SHAP with interactive custom-input prediction. "
#         "Users can compare model predictions on the same engineered feature profile, while XGBoost provides the local SHAP explanation view."
#     )
# 
#     # ----------------------------
#     # Top summary metrics
#     # ----------------------------
#     metric_col1, metric_col2, metric_col3 = st.columns(3)
#     with metric_col1:
#         st.metric("Live Prediction Models", "5")
#     with metric_col2:
#         st.metric("SHAP Explainer Model", "XGBoost")
#     with metric_col3:
#         st.metric("Custom Features Controlled", "8")
# 
#     st.divider()
# 
#     # ----------------------------
#     # Global SHAP visuals
#     # ----------------------------
#     target_class_for_summary = "Injection_Exfil_ToolHijack"
#     class_names = list(xgb_label_encoder.classes_)
#     target_idx = class_names.index(target_class_for_summary)
# 
#     shap_values_class_summary = shap_values_3d_summary[:, :, target_idx]
# 
#     expected_value = xgb_explainer.expected_value
#     if isinstance(expected_value, (list, np.ndarray)):
#         base_value_class = expected_value[target_idx]
#     else:
#         base_value_class = expected_value
# 
#     explanation_summary = shap.Explanation(
#         values=shap_values_class_summary,
#         base_values=np.repeat(base_value_class, X_summary.shape[0]),
#         data=X_summary.values,
#         feature_names=X_summary.columns.tolist()
#     )
# 
#     global_mean_abs = np.abs(shap_values_3d_summary).mean(axis=(0, 2))
#     global_importance = (
#         pd.Series(global_mean_abs, index=X_summary.columns)
#         .sort_values(ascending=False)
#     )
# 
#     shap_col1, shap_col2 = st.columns(2, gap="large")
# 
#     with shap_col1:
#         with st.container(border=True):
#             st.subheader("Global SHAP Summary")
#             plt.figure(figsize=(7.2, 4.8))
#             shap.plots.beeswarm(explanation_summary, max_display=10, show=False)
#             plt.title("SHAP Summary — Injection/Exfil/Tool Hijack")
#             plt.tight_layout()
#             st.pyplot(plt.gcf(), clear_figure=True)
# 
#             plot_note(
#                 "The beeswarm plot shows which features most strongly push predictions toward or away from the Injection/Exfil/Tool Hijack class."
#             )
# 
#     with shap_col2:
#         with st.container(border=True):
#             st.subheader("Global Feature Importance")
#             fig, ax = plt.subplots(figsize=(6.5, 4.8))
#             global_importance.head(10).sort_values().plot(kind="barh", ax=ax)
#             ax.set_title("Global Mean Absolute SHAP Values")
#             ax.set_xlabel("Mean |SHAP value|")
#             ax.set_ylabel("")
#             plt.tight_layout()
#             st.pyplot(fig, clear_figure=True)
# 
#             plot_note(
#                 "This bar chart ranks features by overall importance across all classes, highlighting which engineered signals matter most globally."
#             )
# 
#     st.divider()
# 
#     # ----------------------------
#     # Model selection + inputs
#     # ----------------------------
#     config_col1, config_col2 = st.columns([0.95, 1.05], gap="large")
# 
#     with config_col1:
#         with st.container(border=True):
#             st.subheader("Choose a Model")
# 
#             model_choice = st.selectbox(
#                 "Select which model to use for prediction",
#                 ["XGBoost", "Logistic Regression", "Decision Tree", "Random Forest", "MLP"],
#                 key="tab4_model_choice"
#             )
# 
#             plot_note(
#                 "The selected model controls the class prediction below. The local SHAP waterfall remains tied to XGBoost, since Part 3 explainability was built on the best-performing tree-based model."
#             )
# 
#     with config_col2:
#         with st.container(border=True):
#             st.subheader("Custom Input Strategy")
#             st.write("""
#             The user manually sets a small set of high-value engineered features. All remaining features are filled using dataset-average defaults.
#             """)
#             plot_note(
#                 "This allows for handling many features without overwhelming the user interface."
#             )
# 
#     st.divider()
# 
#     input_col1, input_col2 = st.columns(2, gap="large")
# 
#     with input_col1:
#         with st.container(border=True):
#             st.subheader("Structural / Style Features")
# 
#             word_count = st.slider("Word count", min_value=0, max_value=200, value=25)
#             line_count = st.slider("Line count", min_value=1, max_value=20, value=3)
#             punct_density = st.slider("Punctuation density", min_value=0.0, max_value=1.0, value=0.10)
#             caps_ratio = st.slider("Caps ratio", min_value=0.0, max_value=1.0, value=0.05)
# 
#     with input_col2:
#         with st.container(border=True):
#             st.subheader("Attack Indicator Features")
# 
#             override_phrase_count = st.slider("Override phrase count", min_value=0, max_value=10, value=0)
#             secret_keyword_count = st.slider("Secret keyword count", min_value=0, max_value=10, value=0)
#             exfil_phrase_count = st.slider("Exfiltration phrase count", min_value=0, max_value=10, value=0)
#             harm_keyword_count = st.slider("Harm keyword count", min_value=0, max_value=10, value=0)
# 
#     defaults = build_user_input(df)
# 
#     user_features = defaults.copy()
#     user_features["word_count"] = float(word_count)
#     user_features["line_count"] = float(line_count)
#     user_features["punct_density"] = float(punct_density)
#     user_features["caps_ratio"] = float(caps_ratio)
#     user_features["override_phrase_count"] = float(override_phrase_count)
#     user_features["secret_keyword_count"] = float(secret_keyword_count)
#     user_features["exfil_phrase_count"] = float(exfil_phrase_count)
#     user_features["harm_keyword_count"] = float(harm_keyword_count)
# 
#     # Temporary approximation so char_len stays somewhat consistent with word_count
#     user_features["char_len"] = float(word_count * 5)
# 
#     user_input_df = pd.DataFrame([user_features])
#     user_input_df = user_input_df.reindex(columns=feature_cols)
# 
#     with st.container(border=True):
#         st.subheader("Custom Input Feature Vector")
#         st.dataframe(user_input_df, use_container_width=True, hide_index=True)
#         plot_note(
#             "This one-row feature vector is what gets passed into the selected saved model for prediction."
#         )
# 
#     # ----------------------------
#     # Prediction button + outputs
#     # ----------------------------
#     if st.button("Generate Custom Input for Prediction", key="tab4_predict_button"):
# 
#         if model_choice == "XGBoost":
#             pred_encoded = int(xgb_model.predict(user_input_df)[0])
#             pred_raw = xgb_label_encoder.inverse_transform([pred_encoded])[0]
# 
#             proba = xgb_model.predict_proba(user_input_df)[0]
#             proba_df = pd.DataFrame({
#                 "Class": [display_class_map.get(c, c) for c in xgb_label_encoder.classes_],
#                 "Probability": proba
#             }).sort_values("Probability", ascending=False).reset_index(drop=True)
# 
#         elif model_choice in sklearn_models:
#             selected_model = sklearn_models[model_choice]
# 
#             pred_raw = selected_model.predict(user_input_df)[0]
#             proba = selected_model.predict_proba(user_input_df)[0]
# 
#             proba_df = pd.DataFrame({
#                 "Class": [display_class_map.get(c, c) for c in selected_model.classes_],
#                 "Probability": proba
#             }).sort_values("Probability", ascending=False).reset_index(drop=True)
# 
#         elif model_choice == "MLP":
#             X_input_scaled = mlp_scaler.transform(user_input_df)
#             proba = mlp_model.predict(X_input_scaled, verbose=0)[0]
# 
#             pred_encoded = int(np.argmax(proba))
#             pred_raw = mlp_label_encoder.inverse_transform([pred_encoded])[0]
# 
#             proba_df = pd.DataFrame({
#                 "Class": [display_class_map.get(c, c) for c in mlp_label_encoder.classes_],
#                 "Probability": proba
#             }).sort_values("Probability", ascending=False).reset_index(drop=True)
# 
#         pred_display = display_class_map.get(pred_raw, pred_raw)
# 
#         with st.container(border=True):
#             render_prediction_outputs(pred_display, proba_df, model_choice)
#             plot_note(
#                 f"This prediction uses the saved {model_choice} model and the same engineered feature structure used during training. "
#                 "The user manually controls a handful of important features, while the remaining features are filled with dataset-average defaults."
#             )
# 
#         st.divider()
# 
#         with st.container(border=True):
#             st.subheader("Local SHAP Explanation for This Input")
# 
#             xgb_pred_encoded = int(xgb_model.predict(user_input_df)[0])
#             xgb_pred_raw = xgb_label_encoder.inverse_transform([xgb_pred_encoded])[0]
#             xgb_pred_display = display_class_map.get(xgb_pred_raw, xgb_pred_raw)
# 
#             xgb_pred_class_idx = class_names.index(xgb_pred_raw)
#             custom_explanation = get_multiclass_shap_for_class(
#                 xgb_explainer,
#                 user_input_df,
#                 xgb_pred_class_idx
#             )
# 
#             left_pad, center_col, right_pad = st.columns([0.08, 0.84, 0.08])
# 
#             with center_col:
#                 plt.figure(figsize=(8, 4.8))
#                 shap.plots.waterfall(custom_explanation[0], max_display=8, show=False)
#                 plt.title(f"SHAP Waterfall — XGBoost ({xgb_pred_display})")
#                 plt.tight_layout()
#                 st.pyplot(plt.gcf(), clear_figure=True)
# 
#             plot_note(
#                 "This waterfall plot uses the XGBoost model from Part 3 to show how the custom feature values push the prediction toward or away from the predicted class."
#             )